-- Tabla de usuarios
CREATE TABLE IF NOT EXISTS "User" (
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  name VARCHAR(255),
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabla de rifas
CREATE TABLE IF NOT EXISTS "Rifa" (
  id SERIAL PRIMARY KEY,
  numero VARCHAR(255) UNIQUE NOT NULL,
  descripcion TEXT,
  ganador VARCHAR(255),
  estado VARCHAR(50) DEFAULT 'activo',
  "userId" INT NOT NULL,
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("userId") REFERENCES "User"(id) ON DELETE CASCADE
);

-- Crear índices
CREATE INDEX IF NOT EXISTS idx_user_id ON "Rifa"("userId");
CREATE INDEX IF NOT EXISTS idx_numero ON "Rifa"(numero);
CREATE INDEX IF NOT EXISTS idx_estado ON "Rifa"(estado);
